### ISSUE TITLE
Failed to build Android APK

### ISSUE THREAD

**Issue by bafu** [me-box/databox-app#8]
Run the following command and will get the error messages: 

```
$ npm run-script build

> io.databox.app@0.5.0 build /home/debug/codes/databox/databox-app
> pug-module src/templates/*.pug -o src/js/templates.js; pug src/*.pug -o www/; browserify src/app.js -o www/js/bundle.js

File src/js/templates.js has been saved!

  rendered /home/debug/codes/databox/databox-app/www/index.html
Error: Cannot find module 'Navigo' from '/home/debug/codes/databox/databox-app/src/js'
    at /home/debug/codes/databox/databox-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/debug/codes/databox/databox-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/debug/codes/databox/databox-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/debug/codes/databox/databox-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/debug/codes/databox/databox-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/debug/codes/databox/databox-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! io.databox.app@0.5.0 build: `pug-module src/templates/*.pug -o src/js/templates.js; pug src/*.pug -o www/; browserify src/app.js -o www/js/bundle.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the io.databox.app@0.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/debug/.npm/_logs/2018-12-27T16_57_03_245Z-debug.log
```

---
Environment

* Databox App: commit `f1a8f8f`

**Comment by mor1** [comment]
@bafu Thanks! I see your PR #9 fixes this; we'll try and merge it once the repo moves are sorted.

**Comment by ktg** [comment]
No longer relevant with the new version of the app
